export const  doiTypes = [
    "Audiovisual",
    "Award",
    "Book",
    "Book chapter",
    "Collection",
    "Computational notebook",
    "Conference paper",
    "Conference proceeding",
    "Data paper",
    "Dataset",
    "Dissertation",
    "Event",
    "Image",
    "Instrument",
    "Interactive resource",
    "Journal",
    "Journal article",
    "Model",
    "Output management plan",
    "Peer review",
    "Physical object",
    "Preprint",
    "Project",
    "Report",
    "Service",
    "Software",
    "Sound",
    "Standard",
    "Study registration",
    "Text",
    "Workflow",
    "Other"
  ];
  